**1.** Write a Python Program to Add Two Matrices?

**Answer:**

In [2]:
import numpy as np

A = np.array([[1, 2, 3], [2, 5, 4]])
B = np.array([[7, 2, 6], [2, 2, 4]])

A + B

array([[8, 4, 9],
       [4, 7, 8]])

**2.** Write a Python Program to Multiply Two Matrices?

**Answer:**

In [8]:
A = np.array([[1, 2, 3], [2, 5, 4]])
B = np.array([[7, 2, 6], [2, 2, 4], [2, 4, 1]])

np.array([[sum([A[i, k]*B[k, j] for k in range(B.shape[1])]) 
           for j in range(B.shape[1])] 
          for i in range(A.shape[0])])

array([[17, 18, 17],
       [32, 30, 36]])

**3.** Write a Python Program to Transpose a Matrix?

**Answer:**

In [9]:
A = np.array([[1, 2, 3], [2, 5, 4]])

np.array([[A[j, i] for j in range(A.shape[0])] for i in range(A.shape[1])])

array([[1, 2],
       [2, 5],
       [3, 4]])

**4.** Write a Python Program to Sort Words in Alphabetic Order?

**Answer:**

In [10]:
words = ['cat', 'dog', 'bird', 'cry', 'run']
    
sorted(words)

['bird', 'cat', 'cry', 'dog', 'run']

**5.** Write a Python Program to Remove Punctuation From a String?

**Answer:**

In [12]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

text = "I decided to take a break, but I wasn't able to."

for i in text:
    if i in punctuations:
        text = text.replace(i, '')
        
text

'I decided to take a break but I wasnt able to'